[compiler.solc]
exclude_paths = ["script", ".venv", "lib", "node_modules", "test", "venv"]
include_paths = ["node_modules"]

[compiler.solc.optimizer]
runs = 200

[detectors]
exclude = []
ignore_paths = ["test", "venv", ".venv"]
exclude_paths = ["script", ".venv", "lib", "node_modules", "test", "venv"]

[testing]
cmd = "anvil"

[testing.anvil]
cmd_args = "--prune-history 100 --transaction-block-keeper 10 --steps-tracing --silent"

[testing.ganache]
cmd_args = "-k istanbul -q"

[testing.hardhat]
cmd_args = ""